apiVersion: v1
kind: Service
metadata:
  name: stock-microservice-service
spec:
  selector:
    app: stock-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort